### PR TITLE
3 lanes added to background

### PR DESCRIPTION
**Pull request by ghartle3**
Added 3 lanes to background using the line function from p5.js

### CODE REVIEW

**Comment by WolfWindOW** [comment]
I dont think this pull request does anything, double check that the changes are committed

**Comment by ghartle3** [comment]
You're right, forgot to commit. Just did. My bad

**Review by WolfWindOW — APPROVED** [review]
Looks good.

Note: we may want to swap it over to procedural, based on the canvas size, rather than hard code it

**Comment by ghartle3** [comment]
That a good idea. Do you have any advice on how I should go about doing that?

**Pull request merged**
